### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by lucthev** [lucthev/compose#77]
Individual items can be spun out as separate issues as needed.

- [x] Copy/cut handler
- [ ] Paste handler (partially done; needs a way to intercept paste events?)
- [x] Inline formatter
- [ ] Type-over handler (when multiple paragraphs are selected and the user enter some text, the View has to be updated)
- [ ] Undo/redo
- [x] Full support for IME composition
- [ ] An init method. Ideally, this should have a strict and a “lax” mode. This should be a part of some kind of rich text mode.
- [ ] Preventing drag & drop reordering of text, while still allowing images.

Additionally, some nice to haves:
- [ ] Smart text
- [ ] A plugin for adding first/last paragraph/section classes
- [ ] Placeholders
- [ ] A (floating?) toolbar plugin
- [ ] Hanging punctuation
- [ ] Max length?

Long term, but these can be spun out into separate issues at a later date:
- [ ] Images
- [ ] Embeds
